add some formatting to release script

diff --git a/release-version b/release-version
--- a/release-version
+++ b/release-version
@@ -6,11 +6,21 @@ set -e
 # semver version to release
 VERSION=$1
 
+# formatting vars
+term=${TERM:-"dumb"}
+red=$(tput -T$term setaf 9)
+green=$(tput -T$term setaf 10)
+yellow=$(tput -T$term setaf 11)
+blue=$(tput -T$term setaf 12)
+white=$(tput -T$term setaf 15)
+bold=$(tput -T$term bold)
+normal=$(tput -T$term sgr0)
+
 # test cli param and print usage information
 if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-  printf "Upgrade node.js version and release new images.\n"
-  printf "Usage: $(basename "$0") <SEMVER_VERSION>\n"
-  printf "Example: $(basename "$0") 8.11.2\n"
+  printf "Upgrade dockerfiles to given node.js version and release new images.\n\n"
+  printf "Usage: ${white}${bold}$(basename "$0") <SEMVER_VERSION>${normal}\n\n"
+  printf "Example: ${white}${bold}$(basename "$0") 8.11.2${normal}\n"
   exit 1
 fi
 
@@ -18,18 +28,18 @@ fi
 cd "$(dirname "$0")"
 
 # test if git is available
-command -v git >/dev/null 2>&1 || { printf >&2 "git is required but not available.\nAborting.\n"; exit 1; }
+command -v foo >/dev/null 2>&1 || { printf >&2 "${red}git is required but not available.${normal}\nAborting.\n"; exit 1; }
 
 # test if current branch is master
 CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 if [[ "$CURRENT_BRANCH" != "master" ]]; then
-  printf "Your current git branch should be master but is $CURRENT_BRANCH.\nAborting.\n"
+  printf "${red}Your current git branch should be master but is $CURRENT_BRANCH.${normal}\nAborting.\n"
   exit 1
 fi
 
 # test if working tree is clean
 if REPO_STATUS=$(git status --untracked-files=no --porcelain) && [ ! -z "$REPO_STATUS" ]; then
-  printf "Your git repository seems to have uncommitted changes.\nAborting.\n"
+  printf "${red}Your git repository seems to have uncommitted changes.${normal}\nAborting.\n"
   exit 1
 fi
 
@@ -38,10 +48,10 @@ VERSION_MAJOR=`echo "$VERSION" | sed -E 's/^([0-9]+).+$/\1/'`
 VERSION_MINOR=`echo "$VERSION" | sed -E 's/^([0-9]+\.[0-9]+).+$/\1/'`
 
 # confirm actions
-printf "This script will update all dockerfiles in this repository to node.js version $VERSION.\n"
+printf "This script will update all dockerfiles in this repository to ${yellow}${bold}node.js $VERSION${normal}.\n"
 printf "Changes will be committed, tagged with $VERSION and pushed to GitHub.\n"
 printf "This push should trigger GitHub Actions, where images will be built and released to Docker Hub tagged with $VERSION_MAJOR, $VERSION_MINOR and $VERSION.\n"
-printf "Press [ENTER] to continue or anything else to cancel."
+printf "Press ${white}${bold}[ENTER] to continue${normal} or anything else to cancel."
 IFS= read -s -n 1 key
 echo ""
 if [[ $key != "" ]]; then
@@ -82,7 +92,7 @@ git tag -a $VERSION -m "$MESSAGE"
 git push --tags origin master
 
 # print success message
-printf "\nAll done.\n"
-printf "See GitHub Actions for CI details: https://github.com/simbo/docker-node/actions\n"
-printf "See Docker Hub for released images: https://hub.docker.com/r/simbo/node/tags\n"
+printf "\n${green}All done.${normal}\n"
+printf "See GitHub Actions for CI details: ${blue}https://github.com/simbo/docker-node/actions${normal}\n"
+printf "See Docker Hub for released images: ${blue}https://hub.docker.com/r/simbo/node/tags${normal}\n"
 exit 0
